import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

const Home: NextPage<{ message: string }> = ({ message }) => {
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>{message}</h1>
        <button disabled={!mounted} onClick={() => console.log('YOYOYO')}>
          {mounted ? 'Log' : 'Loading app...'}
        </button>
      </main>
    </div>
  )
}

export async function getServerSideProps() {
  return { props: { message: 'HI!HI!HI!' } }
}

export default Home
